{
 "title": "MySQL Metrics",
 "description": "A dashboard to present MySQL metrics in graph formats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database Uptime (Hours)",
   "type": "stat",
   "description": "The number of hours the MySQL database has been running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_uptime_seconds_total / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Connection Errors (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mysql_connection_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_client_network_io_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Threads",
   "type": "timeseries",
   "description": "The mysql.threads metric in MySQL signifies the current number of threads connected to the MySQL server. These threads can include various types such as client connection threads, replication threads, I/O threads, and more. Understanding this metric is crucial for assessing database performance and resource utilization. Here's how it impacts database performance:",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "mysql_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "mysql_commands_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "InnoDB Operations",
   "type": "timeseries",
   "description": "The number of InnoDB operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "mysql_operations_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Buffer Pool Pages & Data Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "mysql_buffer_pool_data_pages", "legendFormat": "__auto" },
    { "expr": "mysql_buffer_pool_pages", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL & MySQLX Connections (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "mysql_mysqlx_connections_total", "legendFormat": "__auto" },
    { "expr": "mysql_connection_count_total", "legendFormat": "__auto" }
   ]
  }
 ]
}