global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-col"
    scrape_interval: 10s
    static_configs:
      - targets: ["otelcol:8889"] # This should match the endpoint set in your open-telemetry config.yaml file

  - job_name: "mysql-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["mysql-exporter:9104"]
